// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean


// Sexo
export type SexoCreate = {
  nombre_sexo: string
}

export type SexoPublic = {
  nombre_sexo: string
  id: string
}

export type SexosPublic = {
  data: Array<SexoPublic>
  count: number
}

export type SexoUpdate = {
  nombre_sexo: string | null
}

export type SexosReadSexosData = {
  limit?: number
  skip?: number
}

export type SexosCreateSexoData = {
  requestBody: SexoCreate
}

export type SexosReadSexoData = {
  id: string
}
export type SexosUpdateSexoData = {
  id: string
  requestBody: SexoUpdate
}


export type SexosDeleteSexoData = {
  id: string
}

export type SexosUpdateSexoResponse = SexoPublic
export type SexosDeleteSexoResponse = Message
export type SexosReadSexoResponse = SexoPublic
export type SexosCreateSexoResponse = SexoPublic
export type SexosReadSexosResponse = SexosPublic

// Empresa
export type EmpresaCreate = {
  nombre_empresa: string
  direccion: string
  representante_legal: string
  nit: string
  nic: string
  telefono: string
  pagina_web: string
  correo_electronico: string
}

export type EmpresaPublic = {
  id: string
  created_at: Date
  nombre_empresa: string
  direccion: string
  representante_legal: string
  nit: string
  nic: string
  telefono: string
  pagina_web: string
  correo_electronico: string
}

export type EmpresasPublic = {
  data: Array<EmpresaPublic>
  count: number
}

export type EmpresaUpdate = {
  nombre_empresa: string
  direccion: string
  representante_legal: string
  nit: string
  nic: string
  telefono: string
  pagina_web: string
  correo_electronico: string
}

export type EmpresasReadEmpresasData = {
  limit?: number
  skip?: number
}

export type EmpresasCreateEmpresaData = {
  requestBody: EmpresaCreate
}

export type EmpresasReadEmpresaData = {
  id: string
}
export type EmpresasUpdateEmpresaData = {
  id: string
  requestBody: EmpresaUpdate
}

export type EmpresasDeleteEmpresaData = {
  id: string
}

export type EmpresasUpdateEmpresaResponse = EmpresaPublic
export type EmpresasDeleteEmpresaResponse = Message
export type EmpresasReadEmpresaResponse = EmpresaPublic
export type EmpresasCreateEmpresaResponse = EmpresaPublic
export type EmpresasReadEmpresasResponse = EmpresasPublic

// Empleado
export type EmpleadoCreate = {
  primer_nombre: string
  segundo_nombre: string | null
  primer_apellido: string
  segundo_apellido: string | null
  apellido_casada: string | null
  fecha_nacimiento: Date
  fecha_ingreso: Date
  numero_documento: string
  numero_nit: string
  codigo_isss: string
  codigo_nup: string
  salario: number
  id_sexo: string
}

export type EmpleadoPublic = {
  id: string
  created_at: Date
  primer_nombre: string
  segundo_nombre: string | null
  primer_apellido: string
  segundo_apellido: string | null
  apellido_casada: string | null
  fecha_nacimiento: Date
  fecha_ingreso: Date
  numero_documento: string
  numero_nit: string
  codigo_isss: string
  codigo_nup: string
  salario: number
  id_sexo: string
  nombre_sexo: string
}

export type EmpleadosPublic = {
  data: Array<EmpleadoPublic>
  count: number
}

export type EmpleadoUpdate = {
  primer_nombre: string
  segundo_nombre: string | null
  primer_apellido: string
  segundo_apellido: string | null
  apellido_casada: string | null
  fecha_nacimiento: Date
  fecha_ingreso: Date
  numero_documento: string
  numero_nit: string
  codigo_isss: string
  codigo_nup: string
  salario: number
  id_sexo: string
}

export type EmpleadosReadEmpleadosData = {
  limit?: number
  skip?: number
}

export type EmpleadosCreateEmpleadoData = {
  requestBody: EmpleadoCreate
}

export type EmpleadosReadEmpleadoData = {
  id: string
}
export type EmpleadosUpdateEmpleadoData = {
  id: string
  requestBody: EmpleadoUpdate
}

export type EmpleadosDeleteEmpleadoData = {
  id: string
}

export type EmpleadosUpdateEmpleadoResponse = EmpleadoPublic
export type EmpleadosDeleteEmpleadoResponse = Message
export type EmpleadosReadEmpleadoResponse = EmpleadoPublic
export type EmpleadosCreateEmpleadoResponse = EmpleadoPublic
export type EmpleadosReadEmpleadosResponse = EmpleadosPublic
