"""new model empleado

Revision ID: 5cb12efed39a
Revises: e2c40bc8d935
Create Date: 2025-05-26 01:34:10.932251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5cb12efed39a'
down_revision = 'e2c40bc8d935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado',
    sa.Column('primer_nombre', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('segundo_nombre', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('primer_apellido', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('segundo_apellido', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('apellido_casada', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('numero_documento', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('numero_nit', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('codigo_isss', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('codigo_nup', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('salario', sa.Float(), nullable=False),
    sa.Column('id_sexo', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_sexo'], ['sexo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleado')
    # ### end Alembic commands ###
