"""Add modelo puesto trabajo

Revision ID: a173a51e9cbf
Revises: 5cb12efed39a
Create Date: 2025-05-26 13:13:20.477939

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a173a51e9cbf'
down_revision = '5cb12efed39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puestotrabajo',
    sa.Column('nombre_puesto', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('descripcion_puesto', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('salario_limite_inferior', sa.Float(), nullable=False),
    sa.Column('salario_limite_superior', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puestotrabajo')
    # ### end Alembic commands ###
