"""new models empresa empleado sexo unidad

Revision ID: e2c40bc8d935
Revises: 1a31ce608336
Create Date: 2025-05-25 20:46:42.241162

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e2c40bc8d935'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('nombre_empresa', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('representante_legal', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('nit', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('nic', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('pagina_web', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('correo_electronico', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadocivil',
    sa.Column('nombre_estado_civil', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sexo',
    sa.Column('nombre_sexo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sexo')
    op.drop_table('estadocivil')
    op.drop_table('empresa')
    # ### end Alembic commands ###
